name: Test CI/CD

on:
  push:
    branches: [feature/scoped-packages]
  pull_request:
    branches: [feature/scoped-packages]

jobs:
  cloud-deploy:
    runs-on: ubuntu-latest
    continue-on-error: true

    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Install & Build
        run: |
          echo "installing packages and building the repository"
          yarn

      - id: publish
        name: Publish to private repository
        uses: reimagined/github-actions/publish@v1
        with:
          registry: github
          token: ${{ secrets.PUBLISH_ACCESS_TOKEN }}
          version: auto
          build: ${{ github.sha }}
          tag: latest-dev
          unpublish: false

      - name: Checkout resolve-cloud
        uses: actions/checkout@v2
        with:
          repository: DevExpress/resolve-cloud2
          token: ${{ secrets.RESOLVE_CLOUD_CI_PAT }}
          path: resolve-cloud

      - id: cloud
        name: Deploy cloud
        uses: reimagined/github-actions/deploy-cloud@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          stage_name: dev
          version: ${{ steps.publish.outputs.version }}
          path: ./resolve-cloud

      - name: Prepare test application
        run: |
          test_app_dir=$(mktemp -d -t test-app-XXXXXXXXX)
          echo "test_app_dir=${test_app_dir}" >> $GITHUB_ENV
          cp -rf ./functional-tests/app/. ${test_app_dir}
          cd ${test_app_dir}
          rm -rf node_modules

      - id: deploy
        name: Deploy test app to the cloud
        uses: ./.github/actions/deploy
        with:
          resolve_version: ${{ steps.publish.outputs.version }}
          npm_registry: ${{ steps.publish.outputs.registry_url}}
          app_directory: ${{ env.test_app_dir }}
          generate_app_name: true
          resolve_api_url: ${{ steps.cloud.outputs.api_url}}
          resolve_user: ${{ secrets.RESOLVE_CLOUD_USER }}
          resolve_token: ${{ secrets.RESOLVE_CLOUD_TOKEN }}
          deploy_args: --verbosity=debug

      - name: API tests
        run: |
          cd functional-tests
          yarn run-test api --url=${{ steps.deploy.outputs.app_url }}

      - name: Testcafe tests
        run: |
          cd functional-tests
          yarn run-test testcafe --url=${{ steps.deploy.outputs.app_url }} --testcafe-browser=chrome --ci-mode --testcafe-timeout=10000
